version: '3'
services:
  application:
    image: login:1.0.0
    restart: always
    ports:
      - 5432
      - 80:8080
    networks:
      - net

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: item
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432
    networks:
      - net

  cache:
    image: redis:alpine
    restart: always
    ports:
      - 6379
    networks:
      - net

networks:
  net:
    driver: bridge
